<a href="https://colab.research.google.com/github/JoelRomero123/datawarehouse-seguros/blob/main/NOTEBOOKS/Estudiantes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [14]:
url="https://raw.githubusercontent.com/JoelRomero123/etl-data-pipeline-2523552017-/refs/heads/main/RAW/A_estudiantes%20(1).csv"
estudiantes=pd.read_csv(url)
estudiantes.head()

  id_estudiante             nombre edad                      correo
0         E1000         Raúl Gómez   26   carlos.castro45@correo.sv
1         E1001         Ana Castro   18  adriana.santos43@gmail.com
2         E1002   Ricardo Vásquez    23  maria.castro23@empresa.com
3         E1003        Sofía Gómez   27      luis.gomez77@correo.sv
4         E1004     Adriana Santos   26   elena.morales56@gmail.com

In [11]:
#Limpieza de datos estudiantes

estudiante = df.copy()


estudiante.columns = estudiante.columns.str.strip().str.lower()

for col in estudiante.select_dtypes(include='object').columns:
    estudiante[col] = estudiante[col].astype(str).str.strip()

estudiante= estudiante.replace(r'^[\s]*$', pd.NA, regex=True)

estudiante['nombre'] = estudiante['nombre'].str.lower()
estudiante['edad'] = estudiante['edad'].str.lower()
estudiante['correo'] = estudiante['correo'].str.lower()
estudiante=estudiante.drop_duplicates()

In [5]:
#separar datos validos y rechazados
validos = estudiante[
    estudiante['nombre'].notna() &
    estudiante['edad'].notna()&
     estudiante['correo'].notna()
].copy()

rechazados=estudiante[
    estudiante['nombre'].isna() |
    estudiante['edad'].isna()|
     estudiante['correo'].isna()
].copy()

In [7]:
#motivo de rechazo
def motivo(row):

    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")


    if pd.isna(row['edad']):
        motivos.append("edad_vacio")

    if pd.isna(row['correo']):
        motivos.append("correo_vacio")



    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [8]:
#Exportar archivos
validos.to_csv("estudiante_curated.csv", index=False)

rechazados.to_csv("estudiante_rejects.csv", index=False)

In [9]:
#Conectar con PostgreSQL Cloud
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://joel96:EaRTnA1w8VRZFzP2kddKJY6hozj1FcTB@dpg-d6qu6i8gjchc73en5heg-a.oregon-postgres.render.com/etl_seguros_nux8"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 38.9 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [12]:
#Cargar datos en PostgreSQL
validos.to_sql(
    'estudiante_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'estudiante_rejects',
    engine,
    if_exists='append',
    index=False
)

0

In [16]:
#Validar la carga
pd.read_sql(
"SELECT * FROM estudiante_curated LIMIT 10",
engine
)

  id_estudiante            nombre edad                        correo
0         E1000        raúl gómez   26     carlos.castro45@correo.sv
1         E1001        ana castro   18    adriana.santos43@gmail.com
2         E1002   ricardo vásquez   23    maria.castro23@empresa.com
3         E1003       sofía gómez   27        luis.gomez77@correo.sv
4         E1004    adriana santos   26     elena.morales56@gmail.com
5         E1005      carlos pérez   26      diego.perez25empresa.com
6         E1006  valeria martínez   25      luis.romero1@outlook.com
7         E1007     ana hernández   22     elena.romero9@empresa.com
8         E1008    carmen vásquez   21   daniela.morales85@gmail.com
9         E1009      andrés mejía   20  natalia.rivera65@empresa.com